### ISSUE TITLE
Abfrage für Nachts abschalten

### ISSUE THREAD

**Issue by schmarra** [iobroker-community-adapters/ioBroker.solarlog#106]
Hallo,

vielen Dank für den tollen Adapter!

Er funktioniert super mit meinem Solarlog STL 200, bis auf Nachts da erhalte ich immer zwischen 3:00 und 3:02 Uhr den Fehler "Mehrfach fehlerhafter http-Request, Abfragen werden eingestellt, starte Adapter in 90 Sekunden neu neu.".

 Mein Abfrage-Intervall ist auf 10 Sekunden eingestellt, damit ich halbwegs live Werte habe.

Hast du generell mal darüber nachgedacht bzw gibts es bereits eine Möglichkeit Nachts die Abfrage abzuschalten?

**Comment by forelleblau** [comment]
Ja, das kommt vom automatischen Neustart des solarlogs. Offenbar starten unabhängig vom Modell alle Solarlogs morgens um 3.00 Uhr. Nein, bisher habe ich einen Nächtlichen Stopp für den Adapter nicht vorgesehen, er startet ja dann jeweils nach dem Neustart des Solarlogs ebenfalls neu.

**Comment by schmarra** [comment]
Dh der nächtliche Eintrag der Warnung erscheint bei allen und kann nur ignoriert werden?

**Comment by forelleblau** [comment]
Ja genau. Und bisher schien mir eben ignorieren die praktikabelste Lösung....
