### ISSUE TITLE
Please fix issues reported by adapter checker

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.solarlog#166]
👀 [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
 👀 [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
 👀 [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
 👀 [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
 👀 [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

**Comment by forelleblau** [comment]
recheck

**Comment by forelleblau** [comment]
re-check

**Comment by forelleblau** [comment]
completed
