### ISSUE TITLE
Adapter not working with setting "Importieren von Wechselrichter und anderen Gerätedaten"

### ISSUE THREAD

**Issue by joehan112** [iobroker-community-adapters/ioBroker.solarlog#212]
After bringing in one more Inverter to SolarLog15 (latest Firmware), it is no longer possilbe to operate iobroker SolarLog AddIn.
Only if diable setting "Importieren von Wechselrichter und anderen Gerätedaten", it works again. But then there is no detailed Data available. 

See Screenshot on detailed errros.

Thanks in advance for help on this.

Johannes
![solarlogfail](https://github.com/iobroker-community-adapters/ioBroker.solarlog/assets/78538244/722fcd36-3eaf-47a0-abb6-24eb2449fb9f)

**Comment by forelleblau** [comment]
Thanks. Could you please set the adapter log level to 'debug' and provide me a debug-log?
Marcel

**Comment by joehan112** [comment]
Sure. Thanks in advance ;-)
[24-04-20_SolarLog_Debug-LOG.txt](https://github.com/iobroker-community-adapters/ioBroker.solarlog/files/15047474/24-04-20_SolarLog_Debug-LOG.txt)

**Comment by joehan112** [comment]
Thanks for bugfixing this. Work great with new Update :-)
