### ISSUE TITLE
Update stable version in repo to 1.2.2

### ISSUE THREAD

**Issue by GermanBluefox** [iobroker-community-adapters/ioBroker.solarlog#25]
# Think about update stable version to 1.2.2
**Version**: stable=**1.2.1** (62 days old) => latest=**1.2.2** (42 days old)
**Installs**: stable=**112** (45.53%), latest=**60** (24.39%), total=**246**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L1201)

**Comment by forelleblau** [comment]
done
