### ISSUE TITLE
Objekte werden nicht erzeugt.

### ISSUE THREAD

**Issue by Blauschirm1** [iobroker-community-adapters/ioBroker.solarlog#34]
Hallo,
ich weiß nicht ob das hier hin gehört, aber ich habe nach einer Neuinstallation Probleme mit dem Adapter.
Es werden für meine Zähler keine Objekte unter "INV" angelegt und im Log bekomme ich folgende Meldungen:

solarlog.0 | 2020-06-22 12:26:53.064 | warn | (866) Adapter Belkin1 nicht vorhanden
-- | -- | -- | --
solarlog.0 | 2020-06-22 12:26:53.064 | warn | (866) Adapter WR Garage nicht vorhanden
solarlog.0 | 2020-06-22 12:26:53.063 | warn | (866) Adapter WR Haus nicht vorhanden
solarlog.0 | 2020-06-22 12:26:53.062 | warn | (866) Adapter --- nicht vorhanden
solarlog.0 | 2020-06-22 12:26:53.060 | warn | (866) Adapter UV Keller nicht vorhanden
solarlog.0 | 2020-06-22 12:26:53.057 | warn | (866) Adapter Gesamt nicht vorhanden
solarlog.0 | 2020-06-22 12:26:53.056 | warn | (866) Adapter Stefan Garage nicht vorhanden
solarlog.0 | 2020-06-22 12:26:52.462 | warn | (866) Nicht alle WR/Zaehler gefunden
solarlog.0 | 2020-06-22 12:26:50.482 | warn | (866) Adapter Belkin1 nicht vorhanden
solarlog.0 | 2020-06-22 12:26:50.481 | warn | (866) Adapter WR Garage nicht vorhanden
solarlog.0 | 2020-06-22 12:26:50.479 | warn | (866) Adapter WR Haus nicht vorhanden
solarlog.0 | 2020-06-22 12:26:50.478 | warn | (866) Adapter --- nicht vorhanden
solarlog.0 | 2020-06-22 12:26:50.474 | warn | (866) Adapter UV Keller nicht vorhanden
solarlog.0 | 2020-06-22 12:26:50.472 | warn | (866) Adapter Gesamt nicht vorhanden
solarlog.0 | 2020-06-22 12:26:50.471 | warn | (866) Adapter Stefan Garage nicht vorhanden
solarlog.0 | 2020-06-22 12:26:50.467 | warn | (866) Nicht alle WR/Zaehler gefunden
solarlog.0 | 2020-06-22 12:26:48.454 | info | (866) Forecast - Datenabruf: false
solarlog.0 | 2020-06-22 12:26:48.453 | info | (866) Historische Daten werden nicht abgerufen
solarlog.0 | 2020-06-22 12:26:48.452 | info | (866) Unterzähler - Import: true
solarlog.0 | 2020-06-22 12:26:48.446 | info | (866) [START] Starting solarlog adapter
solarlog.0 | 2020-06-22 12:26:48.398 | info | (866) starting. Version 2.0.0 in /opt/iobroker/node_modules/iobroker.solarlog, node: v10.21.0, js-controller: 3.1.4

Ich habe versucht den Adapter neu zu installieren und auch weiter Instanzen davon angelegt, mit dem gleichen Ergebniss.
Was kann ich noch versuchen?

Liebe Grüße
Stefan

**Comment by forelleblau** [comment]
Hallo Stefan
Prüfe bitte einmal, ob deine Sicherheitseinstellung im solarlog mit denen im Adapter übereinstimmen (entweder bei beiden Benutzerpasswort aktiviert oder bei beiden nicht) und ob bei Bedarf das richtige Passwort angegeben ist.

Danke und lieber Gruss Marcel

**Comment by Blauschirm1** [comment]
Hallo Marcel,
danke für deine Antwort.
Die Einstellungen sind soweit in Ordnung. Ich habe zum testen auch mal ein Passwort vergeben, macht keinen Unterschied.
Generell funktioniert die Kommunikation zwischen dem Adapter und dem Solarlog, da mir die Statusdaten angezeigt werden.
Auf einem anderen iobroker hat das ganze auch schon funktioniert, nach einem Hardwaredefekt habe ich nun eine andere Plattform und natürlich aktuelle Versionstände aller Adapter und Systemdateien.
Darauf habe ich mein Backup zurückgespielt.

Gruß
Stefan
![grafik](https://user-images.githubusercontent.com/67270151/85920810-36e7c780-b877-11ea-8e0a-4137d7b9e4de.png)

**Comment by Blauschirm1** [comment]
Hallo Marcel,
ich habe den Adapter mal auf Version 1.3.0 downgegraded (heißt das so?).
Jetzt werden alle WR und Zähler erkannt und deren Objekte angelegt.

solarlog.0 | 2020-06-27 14:18:40.915 | info | (11743) Alle WR/Meter gefunden
-- | -- | -- | --
solarlog.0 | 2020-06-27 14:18:37.920 | warn | (11743) Nicht alle WR/Meter gefunden
solarlog.0 | 2020-06-27 14:18:34.907 | info | (11743) [START] Starting solarlog adapter
solarlog.0 | 2020-06-27 14:18:34.881 | info | (11743) starting. Version 1.3.0 in /opt/iobroker/node_modules/iobroker.solarlog, node: v12.18.1, js-controller: 3.1.6

Danach bin ich wieder auf Version 2.0.0 gegangen und die Objekte werden weiterhin mit den Daten vom Solarlog aktualisiert.

Gruß
Stefan
