### ISSUE TITLE
get detailed information of every inverter

### ISSUE THREAD

**Issue by edelsau-coder** [iobroker-community-adapters/ioBroker.solarlog#37]
hello everyone, 
it would be very nice to get data from every single inverter. daily output in kwh and current output.
who can help? thanks!

**Comment by forelleblau** [comment]
In 'advaced settings' - tab, please check 'Importieren von Wechselrichter- und anderen Gerätedaten' and you shold get what you want and even more.

**Comment by edelsau-coder** [comment]
![image](https://user-images.githubusercontent.com/76178177/102545462-913f4380-40b6-11eb-95cb-3d4d6ac46e01.png)

**Comment by edelsau-coder** [comment]
Seems that there is some problem. i couldnt find detailed information of inverters.

**Comment by forelleblau** [comment]
looks like ;-)
user-pw set in solarlog-adapter? (see readme/security)
What solarlog-model?

**Comment by forelleblau** [comment]
What solarlog-model do you use? There is a similar request with a SL500. Is yours a SL 500 too?

**Comment by forelleblau** [comment]
New version 2.0.1 shold solve your problem. Please install from github.

**Comment by edelsau-coder** [comment]
Hi there.
Very good! It seems that everything is working. Thanks!
