### ISSUE TITLE
Please report solarlog-model compatibility

### ISSUE THREAD

**Issue by forelleblau** [iobroker-community-adapters/ioBroker.solarlog#4]
I'm running the solarlog-adapter with a Solarlog 1200-meter.

I'd like to know on which models of Solarlog (200/300/500/1000/....) the adapter is running sucessfully.

**Comment by Ridesa** [comment]
ein Feld für login daten wäre nicht schlecht habe einen Solarlog 200


solarlog.0 | 2018-11-29 14:00:48.809 | warn | Fehler, noch nicht alle Unterzähler angelegt
-- | -- | -- | --
solarlog.0 | 2018-11-29 14:00:48.808 | warn | Nicht alle WR/Meter gefunden
solarlog.0 | 2018-11-29 14:00:46.789 | warn | Nicht alle WR/Meter gefunden
solarlog.0 | 2018-11-29 14:00:44.765 | warn | Nicht alle WR/Meter gefunden
solarlog.0 | 2018-11-29 14:00:44.340 | warn | ERROR: read ECONNRESET
solarlog.0 | 2018-11-29 14:00:44.216 | warn | ERROR: read ECONNRESET
solarlog.0 | 2018-11-29 14:00:44.213 | warn | ERROR: read ECONNRESET
solarlog.0 | 2018-11-29 14:00:44.212 | warn | ERROR: read ECONNRESET
solarlog.0 | 2018-11-29 14:00:43.159 | warn | Nicht alle WR/Meter gefunden
solarlog.0 | 2018-11-29 14:00:42.305 | warn | ERROR: read ECONNRESET
solarlog.0 | 2018-11-29 14:00:42.111 | warn | ERROR: read ECONNRESET
solarlog.0 | 2018-11-29 14:00:42.108 | warn | ERROR: read ECONNRESET
solarlog.0 | 2018-11-29 14:00:41.409 | warn | ERROR: read ECONNRESET
solarlog.0 | 2018-11-29 14:00:41.379 | warn | ERROR: read ECONNRESET
solarlog.0 | 2018-11-29 14:00:41.338 | warn | ERROR: read ECONNRESET
solarlog.0 | 2018-11-29 14:00:41.338 | warn | ERROR: read ECONNRESET
solarlog.0 | 2018-11-29 14:00:41.337 | warn | ERROR: read ECONNRESET
solarlog.0 | 2018-11-29 14:00:41.337 | warn | ERROR: read ECONNRESET
solarlog.0 | 2018-11-29 14:00:41.336 | warn | ERROR: read ECONNRESET
solarlog.0 | 2018-11-29 14:00:41.327 | warn | ERROR: read ECONNRESET
solarlog.0 | 2018-11-29 14:00:41.324 | warn | ERROR: read ECONNRESET
solarlog.0 | 2018-11-29 14:00:41.314 | warn | ERROR: read ECONNRESET
solarlog.0 | 2018-11-29 14:00:41.197 | warn | ERROR: read ECONNRESET
solarlog.0 | 2018-11-29 14:00:40.699 | warn | Data to request body: {"608":null}
solarlog.0 | 2018-11-29 14:00:40.699 | info | [START] Starting solarlog adapter
solarlog.0 | 2018-11-29 14:00:40.698 | info | starting. Version 0.0.3 in /opt/iobroker/node_modules/iobroker.solarlog, node: v8.12.0
solarlog.0 | 2018-11-29 14:00:36.617 | info | [END] Stopping solarlog adapter...
solarlog.0 | 2018-11-29 14:00:36.589 | info | [END] Stopping solarlog adapter...

**Comment by forelleblau** [comment]
Danke für die Rückmeldung. Soweit mir bekannt ist, kann die json-Schnittstelle nicht mit Passwort geschützt werden.  Seit der Firmware Version  3.5.3 Build 86 muss sie jedoch separat aktiviert werden: Konfiguration - System - Zugangskontrolle - Offene Json-Schnittstelle: akrivieren.

Kann es daran liegen?

**Comment by Ridesa** [comment]
nein daran liegt es nicht da ich mit dem Modbus Adapter drauf zugreife ist die Json-Schnittstelle aktiviert.

**Comment by forelleblau** [comment]
Die Modbus Schnittstelle ist unabhängig von der json. Kannst du bitte im Konfigurationsmenu prüfen, ob die json-Schnittstelle aktiviert ist.

**Comment by Ridesa** [comment]
ist aktiviert

**Comment by forelleblau** [comment]
Für die aktuelle Version, die auch die Unterzähler abfragt, reicht es offensichtlich nicht aus, wenn die JSON-Schnittstelle aktiviert ist. Zusätzlich muss beim Browserzugriffsschutz Stufe Benutzer die Option "Benutzer benötigt Passowort" deaktiviert sein.
Kannst du diese Option einmal deaktivieren und einen weiteren Versuch starten.

Ich arbeite im Moment an einer neuen Version, bei der die Abfrage der Unterzähler optional zugeschaltet werden kann. Ist ein Benutzerpasswort gesetzt und nur die JSON-Schnittstelle aktiviert, können nur die STandard-Werte die in der Dokumentation der JSON-Schnittstelle beschrieben sind, abgerufen werden.

**Comment by forelleblau** [comment]
Version 0.0.5 ist auf Github und npm verfügbar. Damit ist es möglich, die Abfrage der Unterzähler zu deaktivieren und nur mit der JSON-Schnittstelle zu arbeiten

**Comment by JackWolfskin42** [comment]
HI,
hab die aktuelle Version 0.0.5 auch gerade getestet. Selbst mit aktivierter Abfrage der Unterzähler bekomme ich keine in iobroker angezeigt. Sind aber im Solarlog1200 freigegeben und wenn ich sie selber per JS abfrage bekomme ich sie auch.  Ne Idee wie ich beim Debuggen helfen kann?

**Comment by forelleblau** [comment]
Hallo JackWolfskin
Nur zur Sicherheit, bevor wir debug-logs hin und herschicken:
- in deinem solarlog UI sind im Menu "Konfiguration" - "System" - im Tag "Zugangskontrolle" der Punkt "Benutzer benötigt Passowrt" **deaktiviert** und der Punkt "Offene JSON-Schnittstelle" **aktiviert"".

Wenn du für die Stufe "Benutzer" im Solarlog ein Passwort gesetzt hast, geht es nicht.

Wenn beides so eingestellt ist und du bei den solarlog-Objekten im ioBroker keinen INV-Channel mit allen deinen Unterzählern hast, dann bitte einmal in der Instanzen-Seite den solarlog stoppen, die Log-Stufe auf "debug" stellen und wieder starten. Dann bitte das Log an mich, ev. per Mail oder hier als file.

Danke

**Comment by JackWolfskin42** [comment]
Hier nochmal in Kürze: hab die 0.0.6  eben mal getestet und bei mir siehts bis auf den Status = gelb jetzt sehr gut aus. Aktualisierungen aller Geräte klappt wie eingestellt!
Und wirklich alle meine Geräte (WR, S0-Zähler, Belkin-Schalter und Relais werden erkannt ! M.W. ist hiermit dein iobroker Solarlog Adapter der erste der die Solarlogs in dieser Detail-Tiefe auf einer Smart Home Plattform unterstützt!
Vielen Dank für deinen tollen Support !

**Comment by forelleblau** [comment]
Danke für das Feedback, freut mich, wenn es funktioniert!

**Comment by forelleblau** [comment]
Die gelbe Ampel ist geflickt, sie leuchtet in der V0.0.7 jetzt grün. Zusätzlich werden neu die Tagessummenwerte für die einzelnen Unterzähler erfasst.

**Comment by Wiggins2610** [comment]
Hallo. Ich habe ebenfalls einen Solarlog200, aktuelle FW ist 3.6.0 Build 97 - 18.12.2018. 
Es wandern keine Daten zu meinem iobroker. Adapter ist grün, alle 3 werte stehen auf wahr.
Es ist kein Benutzerpasswort gesetzt, ebenso ist JSON aktiviert. Was mach ich nur falsch?

Das taucht bei mir im iobroker Log auf: 
**ERROR ReqDataStandard: getaddrinfo ENOTFOUND http://192.xxx.xxx.xx http://192.xxx.xxx.xx:80**

Kann mir jemand helfen? 
Danke schonmal

**Comment by forelleblau** [comment]
Hallo Winggis2610
Die Meldung bedeutet, dass er den angegebenen Server nicht findet.
Wenn ich von vorne beginne könnte in dem Fall
- die IP nicht stimmen oder nicht so eingegeben sein, wie es der Adapter braucht (die Ampel wird auch wenn ich bei mir eine falsche IP eingebe grün). Falls du bei der Konfiguration die IP mit "http://" eingegeben hast, so wie oben in der Fehlerbeschreibung, dann bitte ich dich, einmal nur die Zahlen, getrennt mit Punkten, also z.B. 192.168.0.101 einzugeben. Das wäre das Format, mit dem der Adapter arbeiten kann. Werde das noch so ins readme/Feldlabel aufnehmen.
Danke für den Hinweis und eine Rückmeldung falls damit der Fehler behoben ist.
Herzliche Grüsse
Forelleblau

**Comment by Wiggins2610** [comment]
Guten Morgen, 
funktioniert jetzt. Mega. Danke für Deine Hilfe. 
Hier also nun Solarlog 200 BT im Einsatz und funzt! Danke für den Adapter! 
Herzliche Grüße, Wiggins

**Comment by forelleblau** [comment]
Gern geschehen, danke für die Rückmeldung.

**Comment by philoxio** [comment]
Hi!
Solar Log 50 funktioniert, allerdings wird im Ordner info und Status "ACCESS DENIED" eingetragen. Wechselrichter wurden allerdings erkannt und es kommen auch Werte an.
Danke @forelleblau top Adapter!

**Comment by forelleblau** [comment]
Hallo 
Könnten bitte einige von euch hier

[https://forum.iobroker.net/topic/26393/test-adapter-solarlog-v1-0-x-latest](https://forum.iobroker.net/topic/26393/test-adapter-solarlog-v1-0-x-latest)

und ev. hier, je nach installierter Version

[https://forum.iobroker.net/topic/26395/test-adapter-solarlog-v1-1-x-github](https://forum.iobroker.net/topic/26395/test-adapter-solarlog-v1-1-x-github)

Feedback hinterlassen. Insbesondere für v1.0.0 wäre es wichtig, damit die ins stable repo kann.
Danke

**Comment by forelleblau** [comment]
Hallo
Im latest - repo ist eine neue Version verfügbar. Die zeigt nun Daten zum Eigenverbrach über verschiedene Zeitperioden, eine ganze Menge historischer Daten und eine Lösung für Vorhersagedaten (von Forecast.solar) an.

Für einen Test und einen Eintrag unter
[https://forum.iobroker.net/topic/27793/test-adapter-solarlog-v1-2-x-latest](https://forum.iobroker.net/topic/27793/test-adapter-solarlog-v1-2-x-latest)

bin ich euch dankbar, damit die Version anschliessend ins stable - Repo kann.

Herzliche Grüsse
Marcel

**Comment by forelleblau** [comment]
Hallo

Es gibt eine neue Version, die nun den Betrieb mit aktiviertem Benutzerpasswort ermöglicht

[Test Version 1.3.0](https://forum.iobroker.net/topic/31425/test-adapter-solarlog-v1-3-x-latest)

Herzliche Grüsse
Marcel
