### ISSUE TITLE
Smart Relais Box

### ISSUE THREAD

**Issue by andreas0022** [iobroker-community-adapters/ioBroker.solarlog#40]
Der Adapter funktioniert mit fast allem super! ich habe beim SL1200 noch die Smart Relais Box angeschlossen wird. diese wird in den Objekten auch erkannt, aber nur mit minimalen Daten. Es sind nur folgende Datensätze vorhanden:

PAC (ist immer 0W)
daysum (auch immer 0Wh)
devicebrand
deviceclass
devicetyp
status (ist immer auf "Off") 

Die Relaisbox an sich funktioniert einwandfrei, sie schaltet die Relais, wie sie soll...

nun möchte ich aber die Relais über iobroker schalten, bzw. eigentlich nur deren Status auslesen, ob eingeschaltet oder ausgeschaltet.

es ist diese Relais box:
https://www.solar-log.com/de/produkte-komponenten/solar-logTM-komponenten/smart-plug-relais/#section__uid--960

Danke, Andreas

**Comment by forelleblau** [comment]
Hallo Andreas
Danke für den Hinweis. Ein paar Fragen dazu:
- Stimmen 'devicebrand, -class, und typ' oder kommen da auch keine Werte rein?
- Wo in der Solarlog - Benutzeroberfläche kannst du a) den Status und b) den Verbrauch auf dem Relais sehen? Unter Ertragsdaten/Momentanwerte/Tabelle oder unter einem anderen Menupunkt?

Wenn ich das richtig sehe, schaltet die Relais-Box zwar, misst aber keine Verbräuche, das würde erklären, warum die Werte leer bleiben. Zumindest die korrekte Statusanzeige - falls du die in der Solarlog - Benutzeroberfläche irgendwo siehst, sollte aber machbar sein.

Mit 'Schaltversprechen' bin ich vorsichtig. Da versuche ich mich ab und zu dran, hab aber auch schon meinen solarlog 'abgeschossen'. Geh mal davon aus, dass es vorläufig beim Auslesen von Werten bleibt.

Herzliche Grüsse
Marcel

**Comment by andreas0022** [comment]
Hallo Marcel, 
danke für die rasche Antwort.
der Schaltstatus der Box, sowie noch andere Schalter sind hier sichtbar:

![image](https://user-images.githubusercontent.com/54526221/111043593-a1f81f00-8443-11eb-9c80-2f6ddf32a15e.png)

ich habe noch einige Belkin Wemo Insight Switches, welche im iobroker aber problemlos erkannt werden, auch deren Schaltstatus.

Es stimmt, die Box schaltet nur Relais und steuert potentialfreie Kontakte, weshalb natürlich kein Verbrauch messbar ist.

so sieht die Anzeige in den Objekten aus:

![image](https://user-images.githubusercontent.com/54526221/111043727-5db94e80-8444-11eb-9f48-78456fd74650.png)

Im Vergleich zur einem Wemo (siehe Wemo1-Boiler1) werden die gleichen Daten angezeigt. Beim Datensatz "status" wird dann auch "on" oder "off" richtig angezeigt. 
Bei der Smart Relais Box, bleibt status immer auf off. die einzelnen Relais werden in den Schaltgruppen per Überschusssteuerung geschaltet.

![image](https://user-images.githubusercontent.com/54526221/111043872-59d9fc00-8445-11eb-878b-f86841c32531.png)


Vielen Dank und schöne Grüße, Andreas

**Comment by forelleblau** [comment]
Hallo Andreas
Bin grad dran, ob ich rausfinde, wo die Information zur 'Hardware' unter 'Smart Energy' steckt. Der Solarlog gibt sich aber sperrig.
Die Schaltgruppen (Kasten unter 'Hardware') könnte ich mit 'Status' (Name der Schaltgruppe, Schalter ON/OFF/AUTO, und Schaltbild ON/OFF) abbilden. Da hab ich was gefunden.
Das wär auch schon was, oder?

Herzliche Grüsse
Marcel

**Comment by andreas0022** [comment]
Ich würde sagen, das ist nicht nur etwas, sondern das wäre bereits die Lösung!
Vielen, vielen Dank und schöne Grüße aus Südtirol!

**Comment by forelleblau** [comment]
Hallo Andreas

Ging einfacher als gedacht. Die neue Version 2.0.2. ist auf github verfügbar, du musst sie direkt von dort installieren.
Sie bildet die Schaltgruppen als Kanäle ab und für jede Schaltgruppe ein 'mode' Objekt, dass den Stand des Schalter (on/off/auto) anzeigt und ein 'state' Objekt, dass das Schaltbild (im Moment nur ganz rot oder ganz grün / off/on) abbildet.

Kannst du das bitte mal testen?

Schönen Gruss aus dem Emmental in Südtirol

Marcel

**Comment by andreas0022** [comment]
Hi Marcel!
oh, das ging schnell! habe getestet, die Schaltgruppen und Kanäle (mode und state) werden angezeigt. bei "mode" bekomme ich keinen Wert herein. Bei "state" bekomme ich den Wert nur von den "Einzelgeräten" (z.B. Wemo insight switch). Beim 8er Relais bleibt der Status auf "Off". siehe bei Tiefkühlzelle, diese bleibt auf Off, obwohl eingeschaltet.
hier zwei screenshots:

![io1](https://user-images.githubusercontent.com/54526221/111080390-8aca3780-84fe-11eb-9fbd-94e29e3fc616.png)

![io2](https://user-images.githubusercontent.com/54526221/111080395-90c01880-84fe-11eb-9dbb-a3cd27da0a64.png)

habe auch den Adapter mehrmals neugestartet, aber auch den solarlog.
Firmware solarlog ist aktuell 4.2.7

Danke, Andreas

**Comment by forelleblau** [comment]
Hallo Andreas
Schade dass es nicht ganz will, wie es soll, ist ja aber schon mal ein Anfang mit den Objekten.
Könntest du mir ein debug-Log eines adapter - Starts (lange genug warten, bis alle Werte geschrieben sind) zur Verfügung stellen (bitte herunterladen und nicht als screenshot, sonst sehe ich nicht alles). So könnte ich sehen, was dein Solarlog auf die Anfragen für Werte liefert, und wir kommen ev. einen Schritt weiter.

Lieber Gruss und Danke

Marcel

**Comment by andreas0022** [comment]
Genau, der Anfang ist gemacht ;-)

hier der log-Auszug vom Neustart des Adapters:



[debug-log.txt](https://github.com/iobroker-community-adapters/ioBroker.solarlog/files/6137418/debug-log.txt)

ich hoffe, das ist lesbar.

Danke und Grüße, Andreas

**Comment by forelleblau** [comment]
Hallo Andreas
Danke, war bestens zu lesen. Nach diesem Log sollten bei allen Gruppen die Werte ordnungsgemäss eingetragen sein und zwar alle Schalter auf Auto und alle Anzeigen auf OFF/rot. Würde das stimmen, oder müsste das mit dem Schaltbild oben (alle aus ausser Tiefkühlzelle und HZ Abfüll) übereinstimmen.

Ich grüble da gerne noch etwas weiter, bräuchte aber, wie du siehst, deine Unterstützung. Ich hab nur 3 Schaltgruppen und ein einfaches Relais, bei mir hat alles gepasst. 

Könntest du mir ein Schaltbild aus der Solarlog - Oberfläche mit möglichst verschiedenen Zuständen (mind. je ein Schalter an/aus/auto und sowohl rote wie grüne Anzeigen) und eine debug-log vom Adapter - Start mit genau diesen Werten zukommen lassen (oder einfach bestätigen, dass das log oben mit dem Schaltbild weiter oben übereinstimmt).

Dann kann ich mich auf die Suche machen.

Lieber Gruss
Marcel

**Comment by andreas0022** [comment]
Hallo Marcel, 
oh, doch noch spät am Abend arbeiten..
habe nun die neue Version geladen. Jetzt werden die "states" richtig angezeigt. bei "mode" allerdings springt der Wert auf ON(1), ändert sich dann allerdings nicht mehr. er blinkt auch nicht ab und zu grün, er wird sozusagen nicht aktualisiert. 
habe dir nochmal die logs gespeichert, zu folgendem Schaltbild:
die blau eingekreisten sind immer jene vom 8er Relais Board, die anderen sie die Belkin Wemos:

![bild](https://user-images.githubusercontent.com/54526221/111116981-242d3400-8567-11eb-80ab-10e486c3aa20.png)


[2021_03_15_debug-log.txt](https://github.com/iobroker-community-adapters/ioBroker.solarlog/files/6139399/2021_03_15_debug-log.txt)

Benutzerpasswort habe ich keines definiert...

Vielen Dank, Andreas

**Comment by forelleblau** [comment]
Hallo Andreas
Schön scheint jetzt alles zu funktionieren. Gemäss Log werden alle Objekte gemäss dem Schaltbild geschrieben. D.h. die Werte werden korrekt aus dem Solarlog geholt.
Was nicht zu funktionieren scheint, ist das entfernen der Leerschläge beim Anlegen der Objekte. Dem werde ich noch nachgehen (Fehler schon erkannt), da es ev. Probleme verursacht resp. verursachen kann - bei dir scheint es jetzt ja auch mit Leerschlägen zu funktionieren.
Danke vielmal für deine Unterstützung bei der Weiterentwicklung des Adapters.

Herzliche Grüsse
Marcel

**Comment by andreas0022** [comment]
Hallo Marcel,
habe nochmal probiert und es scheint zu funktionieren. Allerdings wurde das letze Relais der 8er Box (Tiefkühlzelle) trotz eingeschaltetem Zustand nur als "OFF" angezeigt. Habe dann die nicht zugewiesenen Relais (grau) einer Schaltgruppe zugeordnet, sodass keine grauen mehr vorhanden waren. jetzt wird auch "Tiefkühlzelle" richtig angezeigt.
Auf jeden Fall bin ich sehr froh, dass das so wunderbar geklappt hat!
Besten Dank und weiterhin gute Arbeit!
Schöne Grüße, 
Andreas

**Comment by forelleblau** [comment]
Hallo Andreas
Das Problem, dass du für die korrekte Anzeige der 'Tiefkühlzelle' die Schaltgruppen füllen musstest habe ich identifiziert und kann es (glaub) lösen.
Ich werde das ganze nun fertigstellen, noch ergänzen mit Objekte zur Anzeige des Verbundene Geräts (Schalter/Relais) inkl 'Untergerät' (Nummer der einzelnen Schalter auf deinem 8er Relais) und wohl wo möglich noch mit dem Verbrauch des Geräts (wird natürlich nur bei den Wemos, wenn die bei dir messen, einen Wert anzeigen), da diese Daten alle im selben Datensatz daherkommen. Ich werde mich dann nochmal melden zum Testen, hoffe, das ist ok.

Lieber Gruss gen Süden

Marcel

**Comment by andreas0022** [comment]
Hallo Marcel!
aber natürlich, gerne melden!
Besten Dank, andreas

**Comment by forelleblau** [comment]
Hallo Andreas

Die Programmdatei ist auf Github aktualisiert. Du könntest von da neu installieren.

Der Adapter sollte nun damit umgehen können, dass z.B. nicht alle Relais zugewiesen sind ('Tiefkühlzellen' - Problem gelöst). Er zeigt zudem an, welche Hardware mit der Schaltgruppe verbunden ist und die Nummer der Unterkomponente, bei deine Relais also Nummer 0 - 7 (sollte zumindest, das kann ich nicht testen).

Kannst du nochmals einen Testlauf machen, gerne auch in der ursprünglichen Konstellation, ohne 'aufgefüllte' Schaltgruppen.

Wenn alles klappt würde ich dann die nächste offizielle Version draus machen und publizieren.

Herzliche Grüsse

Marcel

**Comment by andreas0022** [comment]
Hallo Marcel, super! Ich werde das probieren und dir gleich bescheid geben!
Besten Dank, Andreas

**Comment by andreas0022** [comment]
Hallo Marcel, 
habe die "Ursprungsversion" mit den ungenutzten Relais hergestellt. Jetzt taucht aber die "Tiefkühlzelle" in den Objekten nicht mehr auf. im debug-log ist diesbezüglich eine Warnung vorhanden.
siehe:
[debug-log2.txt](https://github.com/iobroker-community-adapters/ioBroker.solarlog/files/6162026/debug-log2.txt)

Schöne Grüße, Andreas

**Comment by forelleblau** [comment]
Hallo Andreas

Hab das Problem, dass die Tiefkühlzelle nicht angelegt wird (wahrscheinlich) gefunden, hab zuwenig genau nachgearbeitet, sorry. Werde dich nochmals bemühen müssen.

Das viele hin und her tut mir leid. Ich bin Trial and Error Programmierneuling und hab mir das Wissen§3 erst für das Erstellen des solarlog-Adapters 'ergoogelt'. So drehe ich, bis es dann funktioniert, oft ein paar Runden mehr als Profis das wohl tun, was du jetzt 'ausbaden' musst. Ich danke dir für deine Geduld. Ich hoffe, die neue Funktion ist dir das Wert...
Ich melde mich nach der Korrektur.

Lieber Gruss
Marcel

**Comment by andreas0022** [comment]
Nein Marcel, das ist überhaupt kein Problem, ich bin gerne behilflich.
Ich bin selber gar kein Programmierer, ich bin eigentlich Bauer und sonst Hobby-Smart-Home-Bastler... und weil ich mir die Vis der solarlog-Verbrauchsstimmung selber bastle, bin ich natürlich glücklich, dass ich die ganzen Daten über Deinen Solarlog-Adapter zur  Verfügung habe. 
Die neuen Funktionen sind mir das natürlich wert! 
Es kann halt vorkommen, dass manchmal einige Tage nicht dazu komme zum Testen. 
Aber wie gesagt, ich probier gerne.
Danke und schöne Grüße,
Andreas

**Comment by forelleblau** [comment]
Hallo Andreas
Die Fehler sind korrigiert, hoffentlich klappt es nun reibungslos.
Danke fürs Probieren, falls du noch mehr vom Solarlog im Adapter braucht, sag's ruhig. So mach Entwickeln Spass.

Herzliche Grüsse
Marcel

**Comment by andreas0022** [comment]
Hallo Marcel! 
Ja, es sieht jetzt sehr gut aus!
soweit klappt alles!
Besten Dank und schöne Grüße,
Andreas

**Comment by forelleblau** [comment]
Super, danke Andreas.
Dann mach ich mal was offizielles draus.

Beste Grüsse ins Südtirol

Marcel

**Comment by andreas0022** [comment]
Hallo Marcel,
eine andere Bitte:
weißt du, wie ich an diese Werte komme?
- Einspeisung oder Bezug (kW)
- Status ob Einspeisung oder Bezug

bisher habe es ich für die Vis halt einfach mit ein paar Skripten berechnet.

vielleicht gibt der solarlog diese Werte irgendwo direkt aus?

![image](https://user-images.githubusercontent.com/54526221/111975855-590a2f80-8b01-11eb-871b-13bb42659ced.png)


Danke und Grüße, Andreas

**Comment by forelleblau** [comment]
Hallo Andreas
Hab mit deinem neuen Anliegen eine neues Issue eröffnet:

[Ertragsdaten](https://github.com/iobroker-community-adapters/ioBroker.solarlog/issues/42#issue-837974805)

Gruss
Marcel
