### ISSUE TITLE
Ertragsdaten / Momentanwerte / Grafik

### ISSUE THREAD

**Issue by forelleblau** [iobroker-community-adapters/ioBroker.solarlog#42]
Hallo Marcel,
eine andere Bitte:
weißt du, wie ich an diese Werte komme?
- Einspeisung oder Bezug (kW)
- Status ob Einspeisung oder Bezug

bisher habe es ich für die Vis halt einfach mit ein paar Skripten berechnet.

vielleicht gibt der solarlog diese Werte irgendwo direkt aus?

![image](https://user-images.githubusercontent.com/54526221/111975855-590a2f80-8b01-11eb-871b-13bb42659ced.png)

Danke und Grüße, Andreas

_Originally posted by @andreas0022 in https://github.com/iobroker-community-adapters/ioBroker.solarlog/issues/40#issuecomment-803952562_

**Comment by forelleblau** [comment]
Hallo Andreas

Habs angeschaut, ja, die Werte kann ich auslesen. Muss aber mal rankönnen, wenn ich auch Ertrag habe, damit dann die Zuordnung sicher stimmt. Soweit ich es erkennen kann, wird der Bezug gerechnet, dass kann ich aber auch im Adapter zur Verfügung stellen.

Deine Frage hat mich noch auf die Idee gebracht, zwei Abfragezyklen zu realisieren. Neben dem aktuellen, der jeweils etwas länger dauert noch einen 'kurzen Schnellen' mit Ertrags- und Verbrauchdaten, die der Solarlog sehr rasch zur Verfügung stellt. Diese könnte dann z.B. alle 10 - 30 Sekunden abgefragt werden, die anderen alle paar Minuten oder so.

Ich bleib dran.

Gruss Marcel

**Comment by andreas0022** [comment]
Hallo Marcel,
super! dann warte ich wieder auf die "neue" Version ;-)

Danke dir und schöne Grüße,
Andreas

**Comment by andreas0022** [comment]
Hallo Marcel,
hätte noch was gefunden.
im solarlog ist oben links noch so ne Statusanzeige, in der im besten Fall "OK" steht, aber wenn ein Fehler ist, 01 oder 02 usw. angezeigt wird. ist dieser Wert auch noch irgendwo abgreifbar?
![sola1](https://user-images.githubusercontent.com/54526221/112469649-02535e80-8d6a-11eb-8cb9-690c4fec560e.png)
![sola2](https://user-images.githubusercontent.com/54526221/112469660-054e4f00-8d6a-11eb-9b96-ac52a88c2f82.png)


vielen Dank und Grüße, Andreas

**Comment by forelleblau** [comment]
Hallo Andreas
Ich nehme es doch an, dass das geht und nehme dein Bedürfnis mit in die aktuelle Überarbeitung.

Bei dieser Gelegenheit wäre ich froh, wenn ich @gepe2810 als möglichen Tester insbesondere für Darstellung und Einbindung der Batteriewerte begrüssen dürfte - sobald ich dann was zur Verfügung stellen kann. 

Lieber Gruss
Marcel

**Comment by gepe2810** [comment]
ich bin dabei

Gruß
Gerhard

**Comment by forelleblau** [comment]
Hallo Andreas und Gerhard

Bin für den ersten Test bereit: ihr findet auf Github die Version 2.1.0 und die bringt folgendes:

- ein neues Objekt status.feed das den Wert links in der Grafik des Cockpits ausgibt. Ist der Wert positiv wird ins Netz eingespiesen, ist er negativ wird bezogen.
- neu unterschiedliche Intervalle für den Datenabruf. In den Grundeinstellungen kann ein kurzes (ab 10s) Intervall  für den Abruf von Produktions- und Verbrauchsdaten (z.B. Daten in der Grafik aber auch Status der Schalter) definiert werden. In den Erweiterten Einstellungen dann ein Intervall (ab 5 Min) für Summendaten und Durchschnitte, deren Abfrage den solarlog jeweils etwas länger beschäftigt.
- Wenn gewünscht, wäre es ein kleines, die Einspeisung nicht nur über +/- von status.feed sondern zusätzlich über ein Objekt, dass Einspeisung true/false meldet anzugeben.

Mit status.feed, status.pac, status.conspac und den Batteriedaten (wo eine Batterie vorhanden ist) sollten damit alle Werte der Grafik zur Verfügung stehen und in kurzen Intervallen abgerufen werden, ohne das System zu stark zu belasten.

Könnt ihr das bitte mal testen und schauen, ob die Werte in euren Solarlog-Cockpits mit euren Adapterwerten übereinstimmen. Ich hoffe, ich ab das Einberechnen von Batterieladung und -entladung richtig getroffen.


Andreas, an den Displaydaten bin ich dran. Die Symbole und zugehörige Fehler auf dem Bild oben konnte ich entschlüsseln, muss mir aber noch überlegen, wie ich das darstellen soll. Kommt.

Lieber Gruss aus der Schweiz

Marcel

**Comment by forelleblau** [comment]
Hallo ihr beiden

Hab schon etwas nachgearbeitet: 

Neben 'feed' gib es jetzt noch  
- feedin (W Einspeisung) 
- feedinactive (Indikator ob Einspeisung true/false), 
- feedout (W Bezug, damit das auch als Zahl mit positivem Vorzeichen verfügbar ist).

Einige Displaywerte sind verfügbar:

- display.ok, true/false, Anzeige ob im Display OK steht oder nicht
- Icon - Anzeige jeweils off/on/flashing für das WR-, das Netzwerk, das Zähler- und das Nachrichten - Icon
- Zu allen Icons ein Feld mit einer allfälligen Fehlernummer (z.B. wenn das Zähler Icon 'flashing' ist, sollte daneben die 01 oder 02 aus dem Display stehen. Oder die 4 für ER/E4 auf dem Display, wenn die Lan-Verbindung getrennt wird. Was die Fehler bedeuten, muss im Moment noch im Handbuch nachgeschaut werden.

Falls bei euch andere als diese Icons zu sehen sind, könnt ihr mir gerne ein debug-Log und ein Bild vom Display schicken, dann kann ich die Liste noch ausbauen. Bei mir war das alles, was ich identifizieren konnte (weil ich keine anderen Icons auf mein Display gekriegt hab).

Herzliche Grüsse

Marcel

**Comment by andreas0022** [comment]
Hallo Marcel,
vielen Dank für Deine Arbeit!
Es scheint alles zu funktionieren, ich jedenfalls habe keine Mängel feststellen können!
Besten Dank,
Andreas

**Comment by forelleblau** [comment]
Danke, hoffe, das mit den Display-Werten hilft so weiter.

Schönen Sonntag und lieber Gruss
Marcel

**Comment by gepe2810** [comment]
Hallo,
erstmal vielen Dank für deine Arbeit. Der Adapter ist toll.

Heute habe ich das Update eingespielt und auch gleich getestet. Alles funktioniert einwandfrei.

Ich betreibe in meiner Anlage auch eine Batterie.

Bei der Überprüfung der Werte ist mir folgendes aufgefallen:
Solarlog - Anzeige Momentanwerte - Energiefluss:
- Erzeugung     619      821
- Verbrauch      362      351
- Ladung          267      417
- Bezug              10         0
- Einspeisung      0        53
Adapter:
- pac                619       821
- feedin               0           0
- feedout         277       364

Die Solarlog-Anzeige fasst Bezug und Einspeisung an einer Stelle zusammen und ändert entsprechend die Bezeichnung.

Fazit: Die Zahlen stimmen aus Sicht von Solarlog. feedout ist die Summe aus den beiden Zahlen Ladung und Bezug/Einspeisung des Solarlog Adapters. Wenn eine Batterie vorhanden ist, ist es noch nicht das, was mit dem Netz ausgetauscht wird - solange die Batterie geladen bzw. entladen wird. Den echten Bezug/Einspeisung könnte man einfach berechnen, indem man noch die Charpe/Discharge Power der Batterie berücksichtigt. Allerdings haben diese Werte wahrscheinlich das längere Abfrageintervall? Oder kannst du diese Korrektur noch machen? Die Ladeleistung wird auf dem gleichen Solarlog Bild angezeigt.

Grüße und einen schönen Sonntag
Gerhard

**Comment by forelleblau** [comment]
Hallo Gerhard

Danke fürs Installieren und Testen. Eigentlich sollte 'feed' als (Ertrag-Verbrauch)+EntladungBatterie-LadungBatterie berechnet werten, die Batteriedaten werden gleichzeitig (also auch im 'kleinen' Intervall) abgerufen. Das wär dann wenn positiv eine Einspeisung (feedin) oder wenn negativ ein Bezug (feedout = abs(feed))

Was mich etwas irritiert, ist dass du oben sowohl einen Wert für Bezug (100) wie für Einspeisung (53) angegeben hast. Auch wenn es im Verhältnis zur Erzeugung ein Rauschen ist, ist das nach meinem Verständnis nicht möglich. Ist allenfalls der 'Bezug' oben ein 'Entladen' der Batterie?

Kannst du mir bitte einmal ein debug-log einer Abfrage-Sequenz zukommen lassen? 

Schöne Anlage hast du da übrigens, an deinen Verbrauch könntest du noch etwas optimieren ;-)

Lieber Gruss
Marcel

**Comment by gepe2810** [comment]
Hallo Marcel,
da hat die Formatierung ungünstig zugeschlagen. Es sollte eine Tabelle mit 2 Datenreihen sein:
1. Datenreihe: 619, 362, 267, 10, 0 und dann 619, 0, 277
2. Datenreihe: 921, 351, 417, 0, 53 und dann 821, 0, 364

Verbrauch: Heute morgen liefen schon ein paar Verbraucher wie Geschirrspüler, PC, Kühlschrank, Gefrierschränke, etc. Den Verbrauch hab ich ständig im Blick. So gibt es bei mir schon lange keine Glühbirnen mehr, Verbraucher sind über Steckdosenschalter vom Netz getrennt etc. :-)


[Solarlog_Log.txt](https://github.com/iobroker-community-adapters/ioBroker.solarlog/files/6217070/Solarlog_Log.txt)
 

Lieber Gruß
Gerhard

**Comment by forelleblau** [comment]
Danke vielmal Gerhard

Bei meiner Bemerkung zum Verbrauch bin ich natürlich (aufgrund der Formatierung) von 620 **kW** Erzeugung und 360 **kW** Verbrauch ausgegangen....

Leider komm ich noch nicht weiter. Bei deinen Zahlenreihen sind die Werte falsch das ist so. Ich kann mir aber nicht erklären, wie die zustande kommen mit meinen hinterlegten Formeln. Bei der ersten müsste feedin:0 und feedout:10 sein und bei der 2. feedin:53 und feedout:0.

Im angehängten Logfile stimmt die Berechnung aber dann. Dort sehe ich: Erzeugung (status.pac): 2517, Verbrauch (status.conspac): 2589, LadungBatterie (XXX.ChargePower): 124 und es wird ein Bezug von 196 ( (2517-2589-124=-196, feed: -196, feedin:0, feedout:196) errechnet und in die entsprechenden Objekte geschrieben.

Kannst du die Wert von Adapter und Solarlog nochmal vergleichen? Bitte beachte, dass wenn du Adapter und Solarlog-Oberfläche parallel offen hast, du das Bentuzerpasswort inaktiviert haben musst (im SL und im Adapter), weil sich die beiden mit dem Login sonst ständig im Weg stehen.

Wenn es weiterhin falsch Datensätze gibt, bitte einen solchen zusammen mit dem zugehörigen debug log posten, dann finde ich den Fehler ev.

Herzliche Grüsse und Danke
Marcel

**Comment by gepe2810** [comment]
...ich habe eben nochmls Daten erhoben:
- Strom wird aus der Batterie bezogen
- Strom wird aus dem Netz bezogen
- Details siehe Anhänge

Hardcopies mit angezeigten Werten:
[Solarlog_Werte_20210328_2058.docx](https://github.com/iobroker-community-adapters/ioBroker.solarlog/files/6217897/Solarlog_Werte_20210328_2058.docx)

Log-File:
[Solarlog_Log_20210328_2058.txt](https://github.com/iobroker-community-adapters/ioBroker.solarlog/files/6217898/Solarlog_Log_20210328_2058.txt)

Herzliche Grüße
Gerhard

**Comment by forelleblau** [comment]
...danke, das war hilfreich. Jedenfalls habe ich bemerkt, dass die SL-Werte die ich holen, nicht dem entsprechen, was ich vermutet hatte. Es sind offensichtlich Summenwerte aus Erzeugung+Entladung resp. Verbrauch+Ladung und nicht nur Erzeugung und Verbrauch, wie ich vermutet habe. Ohne Batterie ist leider beides das selbe. 
Ich habe den Code nun entsprechend angepasst. Bei mir stimmen die Werte immer noch, aber sie sollten nun bei dir auch richtig berechnet werden, hoffe es zumindest.
Darf ich es dich versuchen lassen? Nur neu von GitHub installieren.

Danke und herzliche Grüsse

Marcel

**Comment by gepe2810** [comment]
...ich bekomme immer noch die Version 2.1.0 - das war doch die Version davor?

Herzliche Grüße
Gerhard

**Comment by forelleblau** [comment]
Hallo Gerhard
Ich hab keine neue Versionsnummer vergeben, nur den Code angepasst. Wenn du den Adapter über 'von GitHub' oder mit dem Link auf GitHub über 'Beliebig' installiert, solltest du up to date sein und hoffentlich richtige Werte erhalten. Ich vergeb eine neue Version jeweils erst, wenn ich eine über npm publiziere.

Lieber Gruss Marcel

**Comment by gepe2810** [comment]
...über 'von GitHub' bekam ich irgendwie nicht den aktualisierten Code. Jetzt habe ich es über 'Beliebig' versucht und siehe da, es hat funktioniert. 

Bis jetzt sieht es gut aus. Die Werte stimmen jetzt mit der Solarlog Anzeige überein. Ich werde es weiter beobachten - vor allem bei unterschiedlichen 'Füllständen' der Batterie.

Vielen Dank schon mal.

Herzliche Grüße
Gerhard

**Comment by gepe2810** [comment]
Hallo Marcel,
ich habe die Werte weiter beobachtet: Sie passen bei allen Konstellationen - Ladezustand und Flussrichtung. 
Allerdings fehlt ein datenpunkt im Kanal der Batterie - siehe Anhang. Würdest du diesen noch erzeugen? Wenn ich es manuell versuche, wird er in einem anderen Kanal (Varta__Element) erzeugt.

[Warnmeldung_Fehlender_Datenpunkt.txt](https://github.com/iobroker-community-
adapters/ioBroker.solarlog/files/6248204/Warnmeldung_Fehlender_Datenpunkt.txt)

Viele Grüße
Gerhard

**Comment by forelleblau** [comment]
Hallo Gerhard

Es ist nicht ein fehlender Datenpunkt, es ist einer der zu viel geschrieben wird. Bei einer Batterie sollte eben nicht .pac geschrieben werden sondern die Batteriewerte (Charge, Discharge, Level).

Sollte jetzt in v2.1.1 behoben sein, hoffe, es funktionert.

Ist jetzt auf Github und in den nächsten Tagen im latest-Repo verfügbar.

Schöne Ostern

Marcel

**Comment by forelleblau** [comment]
Version 2.1.1 auf npm publiziert, steht ab morgen im latest-repo zur Verfügung.
Ich danke euch beiden für die Unterstützung.

Herzliche Grüsse
Marcel

**Comment by andreas0022** [comment]
Hallo Marcel!
super Arbeit! Vielen Dank!
Andreas
