### ISSUE TITLE
Solarlog 200 with Firmware 2.8.1 Build 49 - don't work

### ISSUE THREAD

**Issue by Deinjo** [iobroker-community-adapters/ioBroker.solarlog#43]
Hallo,

ich hab einen Solarlog  mit einer sehr alten Firmware  "2.8.1 Build 49 - 11.12.2012"
Den Konfigurationspunkt für das öffnen der JSON Schnittstelle hab ich nicht.

Im ioBroker bekommen ich folgende Meldung:

```
solarlog.0 | 2021-03-31 14:47:39.391 | warn | (1752) readSolarlogData - Fehler : SyntaxError: Unexpected token < in JSON at position 0
-- | -- | -- | --
solarlog.0 | 2021-03-31 14:47:39.387 | warn | (1752) readSolarlogData - Fehler in standard data request: SyntaxError: Unexpected token < in JSON at position 0
```

Nebeninfo:
Bisher hab ich FHEM benutzt und bin gerade bei dem Umstieg auf ioBroker. Im FHEM hab ich den SolarLog und bekomme alle Werte. Bin mir da aber nicht sicher über welchen Weg das Modul an die Werte kommt.

**Comment by forelleblau** [comment]
Hallo Deinjo.

Soweit ich das eruieren konnte nutzt das fehm modul die modbus-Schnittstelle, das kann der Adapter nicht.
Technisch kenne ich diese firmware nicht.
Was du noch versuchen kannst, ist in den erweiterten Einstellungen den Unterzähler-Import zu aktivieren. So versucht der Adapter Werte auch ausserhalb der offenen Schnittstelle zu holen.
Dann machst du davon ein debug-log und postet es hier. 

Lieber Gruss
Forelleblau

**Comment by hardl1** [comment]
Hallo Forelleblau,

gestern habe ich das erste Mal auf meinem NAS iobroker über Docker installiert.

Es hat prima geklappt mit einem Shelly-Temperatur-addon, die Temperatur ist in der Home-App oben als Temperatur sichtbar.
Jetzt will ich die Ertragswerte eines Solar-log hinzufügen, diese sind im solarlog-Status des iobrokers zu sehen, unter Service/ habe ich zunächst den Wert „solarlog.0.status.uac“ gewählt, aber in home erscheint unter Homebridge nur die Kachel solarlog ohne Werte.
Beim Klick auf die Kachel erscheint „solarlog – Dieses Gerät wird derzeit nicht von der Home-App unterstützt“, unter Bridge -> Geräte = 2 -> und dort steht aber nur nochmals die Temperatur des Shelly-addon.
Was mache ich falsch?

Gruß Reinhard

**Comment by hardl1** [comment]
Hello Trout Blue,

yesterday I installed iobroker on my NAS for the first time via Docker.
It worked great with a Shelly temperature add-on, the temperature is visible as a temperature in the home app.
Now I want to add the yield values ​​of a Solar-log, these can be seen in the solarlog status of the iobroker, under Service I initially selected the value "solarlog.0.status.uac", but in home only the solarlog tile appears under Homebridge without values.
When you click on the tile, “solarlog - this device is currently not supported by the home app” appears under Bridge -> Devices = 2 -> and there is only the temperature of the Shelly addon again.
What am I doing wrong?

Greetings Reinhard

**Comment by forelleblau** [comment]
Hallo Reinhard
Wenn du die solarlog.0.xxx - Werte im ioBroker siehst, dann scheint der solarlog-Adapter zu funktionieren. Mit Homebridge / Home App kenne ich mich nicht aus. Ev. kann dir da jemand aus dem iobroker-Forum weiterhelfen.
Tut mir leid.

Herzliche Grüsse

Marcel

**Comment by hardl1** [comment]
Hallo Marcel,

vielen Dank für die schnelle Antwort, werde ich versuchen.

Gruß
Reinhard
