### ISSUE TITLE
Wrong Types

### ISSUE THREAD

**Issue by skvarel** [iobroker-community-adapters/ioBroker.solarlog#59]
System:
• Node.js: 14.17.5
• NPM: 6.14.14
• Admin: 5.1.24
• js-Controller: 3.3.18

![grafik](https://user-images.githubusercontent.com/1114419/138412474-30f85092-fd88-45af-8b9a-d4d32feca763.png)

**Comment by forelleblau** [comment]
Sorry, dass ich noch nicht geantwortet habe. Mein solarlog ist grad nicht so fit, braucht wohl eine neue SD-Karte.
Ich habe eine angepasste Version auf github geladen, bei der der Fehler nicht mehr auftauchen sollten. Kannst du das sonst mal testen (von github installieren).

Danke

**Comment by skvarel** [comment]
Danke, Läuft :)
