### ISSUE TITLE
CreateObject -> async await

### ISSUE THREAD

**Issue by forelleblau** [iobroker-community-adapters/ioBroker.solarlog#64]
Objekterstellung auf neue SetObjectIfNotExistAsync - Funktionen umstellen zur Fehlervermeidung.

**Comment by GermanBluefox** [comment]
Done. @forelleblau Can you test the actual code?
- got => axios
- Usage of async functions

**Comment by forelleblau** [comment]
Thanks a lot @GermanBluefox ! I opened this issue as a reminder for myself...
Tested, fixed some lines creating errors. Is now running with my hardware. Will ask at least one user with different hardware to test, before publishing as new version outside github.
