### ISSUE TITLE
status.feed in kecontact

### ISSUE THREAD

**Issue by hardl1** [iobroker-community-adapters/ioBroker.solarlog#65]
Hallo,
seit einiger Zeit verwende ich das Objekt solarlog.0.status.feed im Adapter kecontact.0 "Name des States für Netzeinspeisung".
Heute stelle ich fest, dass der Wert im Objekt solarlog.0.status.feed korrekt ist, aber im Objekt kecontact.0.statistics.surplus nicht aktualisiert wird.
Kann das mit der Umstellung auf 2.2.1 zusammenhängen?

**Comment by forelleblau** [comment]
Hallo hardl1
So einfach und abschliessend kann ich dir das wohl nicht sagen. Es ist aber möglich, dass du nach einem Update des Adapters gewisse Verbindungen/Scripts/Einstellungen überprüft werden müssen. Bewusst geändert hätte ich nichts, bin da aber ev. auch zuwenig ioBroker Profi. Kannst du die Verbindung zum anderen Adapter wieder herstellen dass alles läuft wie gewünscht? Der Solarlog-Adapter schreibt einfach das solarlog-Objekt, mehr macht der nicht.

Grüsse
forelleblau

**Comment by hardl1** [comment]
Hallo forelleblau,
hat sich erledigt. Der Adapter keconnect überträgt den feed nicht in surplus, wenn eine Ladepause aktiv ist. Mein Fehler, es fiel zufällig mit dem Update zusammen.

Danke und Grüsse
hardl1
